tests = [
    (True, 2),              
    (True, 3),              
    (False, 4),             
    (True, 17),             
    (False, 18),            
    (False, 1),             
    (True, 29),             
    (False, 30),            
    (True, 97),             
    (False, 100),           
    (False, 0),             
    (False, 4),             
    (True, 11),             
    (True, 13),             
    (False, 15),            
    (True, 89),             
    (False, 21),            
    (False, 22),            
    (True, 73),             
]
