tests = [
    (True, "A man a plan a canal Panama"),     
    (True, "racecar"),                          
    (True, "12321"),                            
    (False, "hello"),                           
    (True, "No lemon, no melon"),               
    (True, "Was it a car or a cat I saw"),      
    (False, "Not a palindrome"),                 
    (True, "Able was I ere I saw Elba"),       
    (False, "This is not a palindrome"),        
    (True, "Madam, in Eden, I'm Adam"),         
    (True, "Never odd or even"),                 
    (True, "Step on no pets"),                   
    (True, "A Toyota's a Toyota"),               
    (False, "This will not work"),               
    (True, "Go hang a salami I'm a lasagna hog"), 
    (False, "Random text"),                      
    (True, "Eva, can I see bees in a cave?"),   
    (True, "Do geese see God?"),                 
    (True, "No 'x' in Nixon"),                   
    (True, "Racecar"),                           
    (True, "Hannah"),                            
    (False, "Hello world"),                      
    (True, "A Santa at NASA"),                  
    (False, "Just a simple text"),               
    (True, "Was it a car or a cat I saw?"),     
    (True, "Never a foot too far, even."),      
    (False, "Python is fun"),                    
    (True, "Do geese see God?"),       
    (True, "Madam in Eden, I'm Adam"),          
    (False, "Sample text"),                      
    (True, "Noon"),                              
    (True, "Taco cat"),                          
    (True, "",),                                 
    (True, " ")
]