tests = [
    (2, "hello"),                          
    (3, "programming"),                    
    (5, "AEIOU"),                          
    (0, "bcdfghjklmnpqrstvwxyz"),         
    (5, "Beautiful"),                      
    (6, "This is an example"),            
    (4, "Python programming"),             
    (8, "I love to code in Python"),      
    (0, ""),                               
    (0, "Rhythm"),                         
    (0, "y"),                              
    (0, "Myth"),                           
    (0, "why"),                            
    (8, "A quick brown fox jumps over"),  
    (5, "The quick brown fox"),           
    (12, "An apple a day keeps the doctor away"),  
    (2, "Zebra"),                          
    (0, "bcdfghjklmnpqrstvwxyz"),         
    (10, "AaEeIiOoUu"),                    
    (3, "Hello World!"),                  
    (5, "1a2e3i4o5u"),                    
    (1, "QWERTY"),                         
]